name: 'Terraform Deploy Module'

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  KEEP_BUILD_UTILS_HOME: /etc/keep-build-utils
  KEEP_DEPLOY_ENV: github_actions

jobs:
  tf-deploy-module:
    name: 'Terraform Deploy Module'
    #    environment: ${{inputs.ENV}}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keep-financial/keep-build-image:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Env
        run: |
          case ${{github.ref}} in
            refs/heads/dev)
              echo 'KEEP_APP_ENV=dev' >> $GITHUB_ENV
            ;;
            refs/heads/stg)
              echo 'KEEP_APP_ENV=stg' >> $GITHUB_ENV
            ;;
            refs/heads/prd)
              echo 'KEEP_APP_ENV=prd' >> $GITHUB_ENV
            ;;
          esac

      - name: Zip module
        run: keep-package-tf-module-in-${{env.KEEP_APP_ENV}}

      - name: Upload module
        run: keep-upload-packaged-tf-module-in-${{env.KEEP_APP_ENV}}
