name: 'Terraform Deploy Root'

on:
  workflow_call:
    inputs:
      KEEP_APP_ENV:
        type: string
        required: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  KEEP_DEPLOY_ENV: github_actions

jobs:
  tf-deploy:
    name: 'Terraform Deploy'
    #    environment: ${{inputs.ENV}}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keep-financial/keep-build-image:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup KEEP_APP_ENV
        shell: bash
        run: |
          if [[ "${{inputs.KEEP_APP_ENV}}" != "" ]]; then
            echo 'KEEP_APP_ENV=${{inputs.KEEP_APP_ENV}}' >> $GITHUB_ENV
            exit 0
          fi
          case ${{github.ref}} in
            refs/heads/dev)
              echo 'KEEP_APP_ENV=dev' >> $GITHUB_ENV
            ;;
            refs/heads/stg)
              echo 'KEEP_APP_ENV=stg' >> $GITHUB_ENV
            ;;
            refs/heads/prd)
              echo 'KEEP_APP_ENV=prd' >> $GITHUB_ENV
            ;;
            refs/heads/cmn)
              echo 'KEEP_APP_ENV=cmn' >> $GITHUB_ENV
            ;;
            *)
              echo 'ERR: Cannot determine env by git ref'
              echo "ERR: Ref - ${{github.ref}}"
              exit 22
            ;;
          esac

      - name: Terraform Init
        run: keep-tf-init-in-${{env.KEEP_APP_ENV}}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: keep-tf-plan-in-${{env.KEEP_APP_ENV}}

      - name: Terraform Apply
        run: keep-tf-apply-in-${{env.KEEP_APP_ENV}}
