name: 'Terraform Deploy Module'

on:
  workflow_call:
    inputs:
      KEEP_APP_ENV:
        type: string
        required: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  KEEP_DEPLOY_ENV: github_actions

jobs:
  tf-deploy-module:
    name: 'Terraform Deploy Module'
    #    environment: ${{inputs.ENV}}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keep-financial/keep-build-image:tst
      credentials:
        username: ${{github.actor}}
        password: ${{github.token}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Env
        run: keep-setup-env-from-branch-ref ${{github.ref}} $GITHUB_ENV ${{inputs.KEEP_APP_ENV}}

      - name: Zip module
        run: keep-tf-package-module-in-env

      - name: Upload module
        run: keep-tf-upload-packaged-module-in-env
