name: 'Terraform Deploy'

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  KEEP_BUILD_UTILS_HOME: /etc/keep-build-utils
  KEEP_DEPLOY_ENV: github_actions
  KEEP_TF_PLAN_OUTPUT_FILE: ./tf-plan
  KEEP_LOG_LEVEL: trace

jobs:
  tf-deploy:
    name: 'Terraform Deploy'
    environment: ${{inputs.ENV}}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keep-financial/keep-build-image:latest
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Env
        run: |
          case ${{github.ref}} in
            refs/heads/dev)
              echo 'KEEP_APP_ENV=dev' >> $GITHUB_ENV
            ;;
            refs/heads/stg)
              echo 'KEEP_APP_ENV=stg' >> $GITHUB_ENV
            ;;
            refs/heads/prd)
              echo 'KEEP_APP_ENV=prd' >> $GITHUB_ENV
            ;;
          esac

      - name: Terraform Init
        run: keep-tf-init-in-${{env.KEEP_APP_ENV}}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: keep-tf-plan-in-${{env.KEEP_APP_ENV}}

      - name: Terraform Apply
        run: keep-tf-apply-in-${{env.KEEP_APP_ENV}}
