name: 'Terraform Deploy'

on:
  workflow_call:
    inputs:
      KEEP_APP_ENV:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  KEEP_DEPLOY_ENV: github_actions
  KEEP_APP_ENV: ${{inputs.KEEP_APP_ENV}}

jobs:
  tf-deploy:
    name: 'Terraform Deploy'
    #    environment: ${{inputs.ENV}}
    runs-on: Larger-Runner-01
    container:
      image: ghcr.io/keep-financial/keep-build-image:tst
      credentials:
        username: ${{github.actor}}
        password: ${{github.token}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Env
        run: keep-setup-env-from-branch-ref ${{github.ref}} $GITHUB_ENV ${{inputs.KEEP_APP_ENV}}

      - name: Terraform Init
        run: keep-tf-init-in-env

      - name: Terraform Validate
        run: keep-tf-validate-in-env

      - name: Terraform Plan
        run: keep-tf-plan-in-env
