name: 'Update ECS Service'

on:
  workflow_call:
    inputs:
      KEEP_APP_ENV:
        type: string
        required: true
      TARGET_SERVICE_ID:
        type: string
        required: true
      TARGET_CLUSTER_ID:
        type: string
        default: main
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  KEEP_DEPLOY_ENV: github_actions
  KEEP_APP_ENV: ${{inputs.KEEP_APP_ENV}}

jobs:
  update-ecs:
    name: 'Terraform Deploy'
    #    environment: ${{inputs.ENV}}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keep-financial/keep-build-image:latest
      credentials:
        username: ${{github.actor}}
        password: ${{github.token}}

    steps:
      # https://github.com/actions/checkout/issues/760
      - name: add safe.directory
        run: git config --global --add safe.directory $PWD

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Env
        run: keep-setup-env-from-branch-ref ${{github.ref}} $GITHUB_ENV ${{inputs.KEEP_APP_ENV}}

      - name: Update ECS Service
        run: keep-update-ecs-service-in-env ${{inputs.TARGET_SERVICE_ID}} ${{inputs.TARGET_CLUSTER_ID}}

