name: 'Update ECS Service'

on:
  workflow_call:
    inputs:
      KEEP_APP_ENV:
        type: string
        required: false
      TARGET_SERVICE_ID:
        type: string
        required: true
      TARGET_CLUSTER_ID:
        type: string
        default: main
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  KEEP_DEPLOY_ENV: github_actions
  KEEP_APP_ENV: ${{inputs.KEEP_APP_ENV}}
  KEEP_ECS_POLL_TICK_INTERVAL: 15000
  KEEP_ECS_POLL_LOCAL_NOTIFICATION: 0

jobs:
  update-ecs:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keep-financial/keep-build-image:tst
      credentials:
        username: ${{github.actor}}
        password: ${{github.token}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Env
        run: keep-setup-env-from-branch-ref ${{github.ref}} $GITHUB_ENV ${{inputs.KEEP_APP_ENV}}

      - name: Update ECS Service
        run: keep-update-ecs-service-in-env ${{inputs.TARGET_SERVICE_ID}} ${{inputs.TARGET_CLUSTER_ID}}

      - name: Poll for completion
        run: keep-poll-cluster-until-all-original-draining-in-env ${{inputs.TARGET_SERVICE_ID}} ${{inputs.TARGET_CLUSTER_ID}}

